
package com.soapworkshop.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://ws.soapworkshop.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.soapworkshop.ws.client.XmlResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processHelloWorldResource", targetNamespace = "http://ws.soapworkshop.com/", className = "com.soapworkshop.ws.client.ProcessHelloWorldResource")
    @ResponseWrapper(localName = "processHelloWorldResourceResponse", targetNamespace = "http://ws.soapworkshop.com/", className = "com.soapworkshop.ws.client.ProcessHelloWorldResourceResponse")
    @Action(input = "http://ws.soapworkshop.com/HelloWorld/processHelloWorldResourceRequest", output = "http://ws.soapworkshop.com/HelloWorld/processHelloWorldResourceResponse")
    public XmlResponse processHelloWorldResource(
        @WebParam(name = "arg0", targetNamespace = "")
        XmlRequest arg0);

}
