//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package com.soapworkshop.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "processHelloWorldResourceResponse", namespace = "http://ws.soapworkshop.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processHelloWorldResourceResponse", namespace = "http://ws.soapworkshop.com/")
public class ProcessHelloWorldResourceResponse {

    @XmlElement(name = "return", namespace = "")
    private com.soapworkshop.ws.XMLResponse _return;

    /**
     * 
     * @return
     *     returns XMLResponse
     */
    public com.soapworkshop.ws.XMLResponse getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(com.soapworkshop.ws.XMLResponse _return) {
        this._return = _return;
    }

}
